### Get All Users
GET http://localhost:3000/user/

### Get One User
GET http://localhost:3000/user/4

### Sign Up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "name": "doston",
  "email": "test3@test3.com",
  "password": "doston"
}

### Sign In
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test3@test3.com",
  "password": "doston"
}

### Update User Status
PATCH http://localhost:3000/user/4

### Delete One User
DELETE http://localhost:3000/user/3