### Get All Users
GET http://localhost:3000/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywibmFtZSI6ImRvc3RvbiIsImVtYWlsIjoidGVzdDNAdGVzdDMuY29tIiwicGFzc3dvcmQiOiJhNzY5OTY3MTQ1ZDUyMjkzLjU1OTk5OGU5Y2VlZTkyMzI4MmY3NjgwM2VkZGIyZjVlNjQ1MmM2YjJiZGM3ZDdkOWU5ZmY1YTZjNTczOWE2N2IiLCJsYXN0TG9naW5UaW1lIjoiVHVlIEp1biAwNiAyMDIzIDE0OjAwOjQ4IEdNVCswNTAwIChVemJla2lzdGFuIFN0YW5kYXJkIFRpbWUpIiwicmVnaXN0cmF0aW9uVGltZSI6IlR1ZSBKdW4gMDYgMjAyMyAxMjozNTowMSBHTVQrMDUwMCAoVXpiZWtpc3RhbiBTdGFuZGFyZCBUaW1lKSIsImlzQWN0aXZlIjp0cnVlLCJpYXQiOjE2ODYwNDIwNDh9._ofhozTskSPLU5IWgQ6PdKzuEbbLXdEsYeDKZCVKYQI

### Get One User
GET http://localhost:3000/user/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6ImRvc3RvbiIsImVtYWlsIjoidGVzdDNAdGVzdDMuY29tIiwicGFzc3dvcmQiOiIwMTMzZmU1YTI0NzY3MzA4LjIzZWY5NjM4MzczNGJhNjM3YzU1ZmViNjZmMjc4NThlM2UyYjU0MGVlODg0Njc2NWZmN2ZiNGQwZjVkNTg1YWUiLCJsYXN0TG9naW5UaW1lIjoiVHVlIEp1biAwNiAyMDIzIDExOjQ3OjQ5IEdNVCswNTAwIChVemJla2lzdGFuIFN0YW5kYXJkIFRpbWUpIiwicmVnaXN0cmF0aW9uVGltZSI6IlR1ZSBKdW4gMDYgMjAyMyAxMTo0NzoyNyBHTVQrMDUwMCAoVXpiZWtpc3RhbiBTdGFuZGFyZCBUaW1lKSIsImlzQWN0aXZlIjp0cnVlLCJpYXQiOjE2ODYwMzQwNjl9.sg7kDBLU9cC2zjcXD2EZM4l5Ok00_ZYkKDAGbwkQxvY

### Sign Up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "name": "doston",
  "email": "test3@test3.com",
  "password": "doston"
}

### Sign In
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test3@test3.com",
  "password": "doston"
}

### Update User Status
PATCH http://localhost:3000/user/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6ImRvc3RvbiIsImVtYWlsIjoidGVzdDNAdGVzdDMuY29tIiwicGFzc3dvcmQiOiIwMTMzZmU1YTI0NzY3MzA4LjIzZWY5NjM4MzczNGJhNjM3YzU1ZmViNjZmMjc4NThlM2UyYjU0MGVlODg0Njc2NWZmN2ZiNGQwZjVkNTg1YWUiLCJsYXN0TG9naW5UaW1lIjoiVHVlIEp1biAwNiAyMDIzIDExOjQ3OjQ5IEdNVCswNTAwIChVemJla2lzdGFuIFN0YW5kYXJkIFRpbWUpIiwicmVnaXN0cmF0aW9uVGltZSI6IlR1ZSBKdW4gMDYgMjAyMyAxMTo0NzoyNyBHTVQrMDUwMCAoVXpiZWtpc3RhbiBTdGFuZGFyZCBUaW1lKSIsImlzQWN0aXZlIjp0cnVlLCJpYXQiOjE2ODYwMzQwNjl9.sg7kDBLU9cC2zjcXD2EZM4l5Ok00_ZYkKDAGbwkQxvY

### Delete One User
DELETE http://localhost:3000/user/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6ImRvc3RvbiIsImVtYWlsIjoidGVzdDNAdGVzdDMuY29tIiwicGFzc3dvcmQiOiI2ZTIxMzY5YWFkODM1NDBkLjA2ZWU1ZTJkMjA4MmM1ZTcyNGIyMzg0NzczZjhhMGIzNzEyNDE3ZDE3MjJiYTY1ODg5YTEzZmM0NWI4ZmFmOTYiLCJsYXN0TG9naW5UaW1lIjoiVHVlIEp1biAwNiAyMDIzIDExOjQ0OjEzIEdNVCswNTAwIChVemJla2lzdGFuIFN0YW5kYXJkIFRpbWUpIiwicmVnaXN0cmF0aW9uVGltZSI6Ik1vbiBKdW4gMDUgMjAyMyAyMTozNjoyOCBHTVQrMDUwMCAoVXpiZWtpc3RhbiBTdGFuZGFyZCBUaW1lKSIsImlzQWN0aXZlIjp0cnVlLCJpYXQiOjE2ODYwMzM4NTN9._XcmCmtInq4UORAuoA_1_nhb6t1L7IymkjMeuU-s8CI
